# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=100, verbose_name='标签名称')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': '导航分组',
                'verbose_name': '导航分组',
            },
        ),
        migrations.CreateModel(
            name='UrlInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='链接名称')),
                ('url_path', models.CharField(max_length=200, verbose_name='链接')),
                ('url_desc', models.TextField(max_length=200, verbose_name='链接描述')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('url_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='app.UrlGroup', verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '导航详情',
                'ordering': ['url_name'],
                'verbose_name': '导航详情',
            },
        ),
    ]
